version: "3.7"

services:
  phoneden:
    build:
      context: .
      dockerfile: ./Phoneden.Web/Dockerfile
      labels:
        com.phoneden.description: "The Phoneden application"
    image: phoneden:latest
    ports:
      - "5010:5005"
    env_file:
      - ./variables.env
    depends_on:
      - database
  database:
    image: postgres:13.0
    ports:
      - "8002:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    env_file:
      - ./variables.env

volumes:
  data-volume:
